### PR TITLE
chore: update packages in `firebase/functions` to fix security vulnerability

### PR DESCRIPTION
**Pull request by nilsreichardt**
Updating packages to newest minor version, to fix the security vulnerability in `path-parser` displayed by GitHub.

### CODE REVIEW

**Comment by nilsreichardt** [comment]
@Jonas-Sander Are the tests failing, because we are using a too new Dart version in CI/CD?

**Comment by Jonas-Sander** [comment]
> @Jonas-Sander Are the tests failing, because we are using a too new Dart version in CI/CD?

Most likely, I didn't hardcode the Dart version in the actions unfortunately.

**Comment by nilsreichardt** [comment]
@Jonas-Sander I created a new PR, where I set the Dart version: https://github.com/SharezoneApp/firebase_auth_token_validation/pull/21

**Comment by nilsreichardt** [comment]
FYI: Setting this PR as draft pull request to be sure, that #21 is first merged.

**Comment by nilsreichardt** [comment]
@Jonas-Sander You can now review again 👍

**Review by Jonas-Sander — APPROVED** [review]

**Comment by Jonas-Sander** [comment]
LGTM :)

**Pull request merged**
